### PR TITLE
timsTOF DIA mode changes

### PR DESCRIPTION
**Pull request by theoplatt**
I don't expect this PR to be accepted (!) but it's a simple hack I had to make so that a timsTOF DIA method run would process through tdf2mzml. It appears that the Precursors table is not created during a DIA method and this causes tdf2mzml to fail badly.

My changes are to circumvent these errors but I doubt the resulting mzml is valid. For my immediate use case it is sufficient, but probably not for others. Plus there is probably a better way to determine the method!

### CODE REVIEW

**Comment by andzajan** [comment]
Hi, sorry for hijacking this PR, but proposed solution will only export full MS data from the file. 
I have never seen any DIA mode file, but my guess would be that precursor information should be in 'DiaFrameMsMsInfo' table 'analysis.tdf' file.

im age

**Comment by mafreitas** [comment]
Will this produce a valid mzML for a DDA data set?

**Comment by mafreitas** [comment]
I will reach out to Bruker as well to confirm support in the SDK and data format.

**Comment by mafreitas** [comment]
@theoplatt  Can you share a DIA data file?

**Comment by theoplatt** [comment]
> @theoplatt Can you share a DIA data file?

Happy to - do you have a place I can push one to?

It does (should) produce valid mzML for DDA as the precursors table will be there and the change is just to skip code when the table is not there. That said - it's not a great solution!

**Comment by mafreitas** [comment]
A possible fix is pushed to branch "dia".

**Pull request closed without merging**
